[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/labstack/echo"
  version = "4.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"
